### ISSUE TITLE
Favicon: missing

### ISSUE THREAD

**Issue by snxx-lppxx** [git/git.github.io#496]
Change default.html #494
```
https://git.github.io/rev_news/rev_news/
https://git.github.io/rev_news/news_sources/
https://git.github.io/rev_news/archive/
```
Maybe create a separate html file?

**Comment by chriscool** [comment]
Yeah, it is strange that both `rev_news/rev_news.md` and `rev_news/news_sources.md` contain `layout: default`, but that the favicon is missing for these pages. We might want to understand why this happens.

**Comment by sivaraam** [comment]
It looks like the culprit is the the relative path reference to the logo:
```html
    <link rel="icon" type="image/x-icon" href="../images/logo.png"/>
```
I don't fully comprehend how path resolution works in Jekyll but it looks changing the relative path reference to an absolute one would make the favicon appear properly for all pages. Like this,

```html
    <link rel="icon" type="image/x-icon" href="/images/logo.png"/>
```

Alternatively, we could have a link to (or) a copy of `images/logo.png` as `favicon.ico` (both appear to work) in the root of the directory. In this way, we don't even need that extra bit of HTML in `default.html`.

**Comment by chriscool** [comment]
@sivaraam yeah, that makes sense! Either solution looks good to me.

Anyway good find, thanks!

**Comment by snxx-lppxx** [comment]
@sivaraam, maybe like this:
```html
<link rel="icon" type="image/x-icon" href="./images/logo.png"/>
```
