### ISSUE TITLE
`git show-branch` isn't listed in "Topics" dropdown

### ISSUE THREAD

**Issue by rybak** [git/git.github.io#511]
`git show-branch` is a builtin command. It has a separate help page: http://git-scm.com/docs/git-show-branch

However, it is not listed in any of the lists in the "Topics" dropdown (browser search for `show` highlighted):

![Screenshot_20210614_225251](https://user-images.githubusercontent.com/624072/121957850-42bbea80-cd63-11eb-9ad0-454dbf1519dc.png)

**Comment by chriscool** [comment]
This repo is for the https://git.github.io web site. The issues related to the https://git-scm web site are there: https://github.com/git/git-scm.com/issues

**Comment by rybak** [comment]
Thanks. My mistake.

While writing a draft of an issue for https://github.com/git/git-scm.com/issues, I realized that there are a lot more builtins, which are not covered in "Topics" (than just `show-branch`). For those, there is a "[Complete list of all commands](https://git-scm.com/docs/git#_git_commands)" linked from https://git-scm.com/docs.

**Comment by peff** [comment]
Yeah, we (folks who work on the git-scm.com repo) have intentionally prioritized keeping the main command list easy to understand rather than comprehensive. If somebody feels strongly about a particular command, it's fine to open an issue there and argue for it, but I think `show-branch` may be an uphill battle ([this message](https://lore.kernel.org/git/xmqq8s3byg7k.fsf@gitster.g/) from this morning matches my feeling :wink:).
